# Form implementation generated from reading ui file 'kthp.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(925, 478)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgba(0, 170, 127, 0.3);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 621, 431))
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("\n"
"color: rgb(0, 0, 127);\n"
"font: 75 7pt \"MS Shell Dlg 2\";\n"
"background-color: rgba(255, 255, 255,0);")
        self.label.setText("")
        self.label.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label.setPixmap(QtGui.QPixmap("img.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.listView = QtWidgets.QListView(parent=self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(710, 70, 191, 191))
        self.listView.setStyleSheet("background-color: rgba(0, 170, 127, 0.3);\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.listView.setObjectName("listView")
        self.them = QtWidgets.QPushButton(parent=self.centralwidget)
        self.them.setGeometry(QtCore.QRect(850, 20, 51, 31))
        self.them.setStyleSheet("background-color: rgba(0, 170, 127, 0.3);\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.them.setObjectName("them")
        self.comboBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(710, 20, 131, 31))
        self.comboBox.setStyleSheet("background-color: rgba(0, 170, 127, 0.3);\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(710, 280, 131, 31))
        self.pushButton.setStyleSheet("background-color: rgba(0, 170, 127, 0.3);\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(110, 70, 21, 16))
        self.label_3.setStyleSheet("\n"
"color: rgb(0, 0, 127);\n"
"font: 75 7pt \"MS Shell Dlg 2\";\n"
"background-color: rgba(255, 255, 255,0);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(210, 100, 35, 10))
        self.label_4.setStyleSheet("\n"
"color: rgb(0, 0, 127);\n"
"font: 75 7pt \"MS Shell Dlg 2\";\n"
"background-color: rgba(255, 255, 255,0);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(160, 70, 21, 16))
        self.label_5.setStyleSheet("\n"
"color: rgb(0, 0, 127);\n"
"font: 75 7pt \"MS Shell Dlg 2\";\n"
"background-color: rgba(255, 255, 255,0);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(290, 130, 35, 10))
        self.label_6.setStyleSheet("\n"
"color: rgb(0, 0, 127);\n"
"font: 75 7pt \"MS Shell Dlg 2\";\n"
"background-color: rgba(255, 255, 255,0);")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(460, 280, 51, 16))
        self.label_7.setStyleSheet("\n"
"color: rgb(0, 0, 127);\n"
"font: 75 7pt \"MS Shell Dlg 2\";\n"
"background-color: rgba(255, 255, 255,0);")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(530, 240, 35, 10))
        self.label_8.setStyleSheet("\n"
"color: rgb(0, 0, 127);\n"
"font: 75 7pt \"MS Shell Dlg 2\";\n"
"background-color: rgba(255, 255, 255,0);")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(570, 170, 35, 10))
        self.label_9.setStyleSheet("\n"
"color: rgb(0, 0, 127);\n"
"font: 75 7pt \"MS Shell Dlg 2\";\n"
"background-color: rgba(255, 255, 255,0);")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(490, 150, 35, 10))
        self.label_10.setStyleSheet("\n"
"color: rgb(0, 0, 127);\n"
"font: 75 7pt \"MS Shell Dlg 2\";\n"
"background-color: rgba(255, 255, 255,0);")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(400, 90, 35, 10))
        self.label_11.setStyleSheet("\n"
"color: rgb(0, 0, 127);\n"
"font: 75 7pt \"MS Shell Dlg 2\";\n"
"background-color: rgba(255, 255, 255,0);")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(330, 80, 41, 16))
        self.label_12.setStyleSheet("\n"
"color: rgb(0, 0, 127);\n"
"font: 75 7pt \"MS Shell Dlg 2\";\n"
"background-color: rgba(255, 255, 255,0);")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(390, 150, 35, 10))
        self.label_13.setStyleSheet("\n"
"color: rgb(0, 0, 127);\n"
"font: 75 7pt \"MS Shell Dlg 2\";\n"
"background-color: rgba(255, 255, 255,0);")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(400, 300, 35, 10))
        self.label_14.setStyleSheet("\n"
"color: rgb(0, 0, 127);\n"
"font: 75 7pt \"MS Shell Dlg 2\";\n"
"background-color: rgba(255, 255, 255,0);")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(420, 220, 61, 16))
        self.label_15.setStyleSheet("\n"
"color: rgb(0, 0, 127);\n"
"font: 75 7pt \"MS Shell Dlg 2\";\n"
"background-color: rgba(255, 255, 255,0);")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(340, 220, 51, 16))
        self.label_16.setStyleSheet("\n"
"color: rgb(0, 0, 127);\n"
"font: 75 7pt \"MS Shell Dlg 2\";\n"
"background-color: rgba(255, 255, 255,0);")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(330, 280, 51, 16))
        self.label_17.setStyleSheet("\n"
"color: rgb(0, 0, 127);\n"
"font: 75 7pt \"MS Shell Dlg 2\";\n"
"background-color: rgba(255, 255, 255,0);")
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(320, 180, 51, 16))
        self.label_18.setStyleSheet("\n"
"color: rgb(0, 0, 127);\n"
"font: 75 7pt \"MS Shell Dlg 2\";\n"
"background-color: rgba(255, 255, 255,0);")
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(420, 380, 35, 10))
        self.label_19.setStyleSheet("\n"
"color: rgb(0, 0, 127);\n"
"font: 75 7pt \"MS Shell Dlg 2\";\n"
"background-color: rgba(255, 255, 255,0);")
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(280, 290, 35, 10))
        self.label_20.setStyleSheet("\n"
"color: rgb(0, 0, 127);\n"
"font: 75 7pt \"MS Shell Dlg 2\";\n"
"background-color: rgba(255, 255, 255,0);")
        self.label_20.setObjectName("label_20")
        self.label_22 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(160, 170, 61, 16))
        self.label_22.setStyleSheet("\n"
"color: rgb(0, 0, 127);\n"
"font: 75 7pt \"MS Shell Dlg 2\";\n"
"background-color: rgba(255, 255, 255,0);")
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(80, 140, 21, 16))
        self.label_23.setStyleSheet("\n"
"color: rgb(0, 0, 127);\n"
"font: 75 7pt \"MS Shell Dlg 2\";\n"
"background-color: rgba(255, 255, 255,0);")
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(230, 200, 35, 10))
        self.label_24.setStyleSheet("\n"
"color: rgb(0, 0, 127);\n"
"font: 75 7pt \"MS Shell Dlg 2\";\n"
"background-color: rgba(255, 255, 255,0);")
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(80, 200, 51, 16))
        self.label_25.setStyleSheet("\n"
"color: rgb(0, 0, 127);\n"
"font: 75 6pt \"MS Shell Dlg 2\";\n"
"background-color: rgba(255, 255, 255,0);")
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(120, 170, 35, 10))
        self.label_26.setStyleSheet("\n"
"color: rgb(0, 0, 127);\n"
"font: 75 7pt \"MS Shell Dlg 2\";\n"
"background-color: rgba(255, 255, 255,0);")
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(30, 210, 35, 10))
        self.label_27.setStyleSheet("\n"
"color: rgb(0, 0, 127);\n"
"font: 75 7pt \"MS Shell Dlg 2\";\n"
"background-color: rgba(255, 255, 255,0);")
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(120, 230, 51, 16))
        self.label_28.setStyleSheet("\n"
"color: rgb(0, 0, 127);\n"
"font: 75 7pt \"MS Shell Dlg 2\";\n"
"background-color: rgba(255, 255, 255,0);")
        self.label_28.setObjectName("label_28")
        self.them_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.them_2.setGeometry(QtCore.QRect(850, 280, 51, 31))
        self.them_2.setStyleSheet("background-color: rgba(0, 170, 127, 0.3);\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.them_2.setObjectName("them_2")
        self.listView_2 = QtWidgets.QListView(parent=self.centralwidget)
        self.listView_2.setGeometry(QtCore.QRect(710, 330, 191, 101))
        self.listView_2.setStyleSheet("background-color: rgba(0, 170, 127, 0.3);\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.listView_2.setObjectName("listView_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 925, 18))
        self.menubar.setObjectName("menubar")
        self.menuB_I_TO_N_NG_I_DU_L_CH_GI_I_THU_T_HILL_CLIMBING = QtWidgets.QMenu(parent=self.menubar)
        self.menuB_I_TO_N_NG_I_DU_L_CH_GI_I_THU_T_HILL_CLIMBING.setStyleSheet("")
        self.menuB_I_TO_N_NG_I_DU_L_CH_GI_I_THU_T_HILL_CLIMBING.setObjectName("menuB_I_TO_N_NG_I_DU_L_CH_GI_I_THU_T_HILL_CLIMBING")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuB_I_TO_N_NG_I_DU_L_CH_GI_I_THU_T_HILL_CLIMBING.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Travelling Salesman Problem"))
        self.them.setText(_translate("MainWindow", "Thêm"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Add"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Crimea"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Donetsk"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Luhansk"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Kharkiv"))
        self.comboBox.setItemText(5, _translate("MainWindow", "Dnlpropetrovsk"))
        self.comboBox.setItemText(6, _translate("MainWindow", "Zaporizhia"))
        self.comboBox.setItemText(7, _translate("MainWindow", "Kherson"))
        self.comboBox.setItemText(8, _translate("MainWindow", "Odessa"))
        self.comboBox.setItemText(9, _translate("MainWindow", "Mykolaiv"))
        self.comboBox.setItemText(10, _translate("MainWindow", "Kirovohrad"))
        self.comboBox.setItemText(11, _translate("MainWindow", "Cherkasy"))
        self.comboBox.setItemText(12, _translate("MainWindow", "Poltava"))
        self.comboBox.setItemText(13, _translate("MainWindow", "Sumy"))
        self.comboBox.setItemText(14, _translate("MainWindow", "Kiev"))
        self.comboBox.setItemText(15, _translate("MainWindow", "Chernihiv"))
        self.comboBox.setItemText(16, _translate("MainWindow", "Zhytomyr"))
        self.comboBox.setItemText(17, _translate("MainWindow", "Vinnytaia"))
        self.comboBox.setItemText(18, _translate("MainWindow", "Chernivtai"))
        self.comboBox.setItemText(19, _translate("MainWindow", "Khmelnytakyi"))
        self.comboBox.setItemText(20, _translate("MainWindow", "Rivne"))
        self.comboBox.setItemText(21, _translate("MainWindow", "Ternopil"))
        self.comboBox.setItemText(22, _translate("MainWindow", "Ivano-Frankivak"))
        self.comboBox.setItemText(23, _translate("MainWindow", "Zakarpattia"))
        self.comboBox.setItemText(24, _translate("MainWindow", "Lviv"))
        self.comboBox.setItemText(25, _translate("MainWindow", "Volyn"))
        self.pushButton.setText(_translate("MainWindow", "TÌM ĐƯỜNG ĐI"))
        self.label_3.setText(_translate("MainWindow", "Volyn"))
        self.label_4.setText(_translate("MainWindow", "Zhytomyr"))
        self.label_5.setText(_translate("MainWindow", "Rivne"))
        self.label_6.setText(_translate("MainWindow", "Kiev"))
        self.label_7.setText(_translate("MainWindow", "Zaporizhia"))
        self.label_8.setText(_translate("MainWindow", "Donetsk"))
        self.label_9.setText(_translate("MainWindow", "Luhansk"))
        self.label_10.setText(_translate("MainWindow", "Kharkiv"))
        self.label_11.setText(_translate("MainWindow", "Sumy"))
        self.label_12.setText(_translate("MainWindow", "Chernihiv"))
        self.label_13.setText(_translate("MainWindow", "Poltava"))
        self.label_14.setText(_translate("MainWindow", "Kherson"))
        self.label_15.setText(_translate("MainWindow", "Dnlpropetrovsk"))
        self.label_16.setText(_translate("MainWindow", "Kirovohrad"))
        self.label_17.setText(_translate("MainWindow", "Mykolaiv"))
        self.label_18.setText(_translate("MainWindow", "Cherkasy"))
        self.label_19.setText(_translate("MainWindow", "Crimea"))
        self.label_20.setText(_translate("MainWindow", "Odessa"))
        self.label_22.setText(_translate("MainWindow", "Khmelnytakyi"))
        self.label_23.setText(_translate("MainWindow", "Lviv"))
        self.label_24.setText(_translate("MainWindow", "Vinnytaia"))
        self.label_25.setText(_translate("MainWindow", "Ivano-Frankivak"))
        self.label_26.setText(_translate("MainWindow", "Ternopil"))
        self.label_27.setText(_translate("MainWindow", "Zakarpattia"))
        self.label_28.setText(_translate("MainWindow", "Chernivtai"))
        self.them_2.setText(_translate("MainWindow", "Xóa"))
        self.menuB_I_TO_N_NG_I_DU_L_CH_GI_I_THU_T_HILL_CLIMBING.setTitle(_translate("MainWindow", "BÀI TOÁN NGƯỜI DU LỊCH - GIẢI THUẬT HILL CLIMBING"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
